[package]
name = "rrr"
version = "0.1.0"
authors = ["Starz0r"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trash = "1.1.1"
anyhow = "=1.0.66"
clap = { version = "=4.0.29", features = ["derive"] }